---

- name: Install zabbix repo
  yum:
    name: http://repo.zabbix.com/zabbix/3.5/rhel/7/x86_64/zabbix-release-3.5-1.el7.noarch.rpm
    state: present

- name: Install zabbix software
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - zabbix-get 
    - zabbix-server-mysql 
    - zabbix-web-mysql 
    - zabbix-agent 

- name: Config Zabbix DB host
  lineinfile: 
    path: /etc/zabbix/zabbix_server.conf
    regexp: '^DBHost='
    line: 'DBHost=localhost'
  notify: restart zabbix
 
- name: Config Zabbix DB password
  lineinfile: 
    path: /etc/zabbix/zabbix_server.conf
    regexp: '^DBPassword='
    line: 'DBPassword=gateway2'
  notify: restart zabbix
 
- name: Start Zabbix service
  service:
    name: zabbix-server
    state: started
    enabled: yes
