---

- name: Install OpenVPN
  apt:
    name: openvpn
    update_cache: yes 
    state: present

- name: Install IPVanish creds file
  template:
    src: "ipvanish.txt.j2"
    dest: "{{ cred_file }}"
  notify: Restart openvpn

- name: Install IPVanish config file
  template:
    src: "OpenVPNConfigFile.conf.j2"    
    dest: "/etc/openvpn/OpenVPNConfigFile.conf"
  notify: Restart openvpn

- name: Install IPVanish cert file
  template:
    src: "ca.ipvanish.com.crt.j2"
    dest: "/etc/openvpn/ca.ipvanish.com.crt"
  notify: Restart openvpn

- name: Install openvpn config file
  template:
    src: "openvpn.j2"
    dest: "/etc/default/openvpn"
  notify: Restart openvpn
    
- name: Start openvpn service
  service:
    name: openvpn
    state: started
    enabled: yes
