---

- name: Install OpenVPN
  apt:
    name: openvpn
    update_cache: yes 
    state: present

- name: Install IPVanish creds file
  template:
    src: "ipvanish.txt.j2"
    dest: "{{ cred_file }}"

- name: Install IPVanish config file
  template:
    src: "OpenVPNConfigFile.conf.j2"    
    dest: "/etc/openvpn/OpenVPNConfigFile.conf"

- name: Install IPVanish cert file
  template:
    src: "ca.ipvanish.com.crt.j2"
    dest: "/etc/openvpn/ca.ipvanish.com.crt"

- name: Install openvpn config file
  template:
    src: "openvpn.j2"
    dest: "/etc/default/openvpn"
    
