---

- name: Install nginx
  apt:
    name: nginx

- name: Enable nginx service
  systemd:
    name: nginx
    daemon_reload: yes
    enabled: yes

- name: Install the nginx config file
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
  notify: restart nginx
