---

- name: Install zabbix repo (CentOS/RHEL)
  yum:
    name: http://repo.zabbix.com/zabbix/3.5/rhel/7/x86_64/zabbix-release-3.5-1.el7.noarch.rpm
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install zabbix repo (Ubuntu 16.04)
  apt:
    deb: http://repo.zabbix.com/zabbix/3.5/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.5-1%2Bxenial_all.deb
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install zabbix software (CentOS/RHEL)
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - zabbix-agent 
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install zabbix software (Ubuntu)
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - zabbix-agent 
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Config Zabbix Agent Server
  lineinfile: 
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^Server='
    line: 'Server=zabbix.glamdring.local'
  notify: restart agent
 
- name: Config Zabbix Agent Server Active
  lineinfile: 
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^ServerActive='
    line: 'ServerActive=zabbix.glamdring.local'
  notify: restart agent
 
- name: Config Zabbix Agent Hostname
  lineinfile: 
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^Hostname='
    line: 'Hostname={{ ansible_fqdn }}'
  notify: restart agent
 
- name: Start Zabbix agent
  service:
    name: zabbix-agent
    state: started
    enabled: yes
