---

- name: Install Apache2
  apt:
    name: apache2
    update_cache: yes

- name: Install mariadb
  apt:
    name: mariadb-server
    update_cache: yes

- name: Set up icinga keys
  apt_key:
    url: https://packages.icinga.com/icinga.key
    state: present

- name: configure icinga repo
  apt_repository:
    repo: deb http://packages.icinga.com/ubuntu icinga-xenial main
    state: present

- name: Install Icinga
  apt:
    name: icinga2
    update_cache: yes

- name: Install Icinga MySQL
  apt:
    name: icinga2-ido-mysql
    update_cache: yes

- name: Install Icinga Web
  apt:
    name: icingaweb2
    update_cache: yes

- name: Start icinga2 service
  service:
    name: icinga2
    state: started
    enabled: yes

- name: Icinga hosts configuration
  template:
    src: etc/icinga2/conf.d/hosts.j2
    dest: /etc/icinga2/conf.d/hosts
    backup: yes
  notify: restart icinga2

