---

- hosts: sensu_masters
  remote_user: root
  vars:
    sensu_master: true
    sensu_include_dashboard: true
    rabbitmq_server: true
    redis_server: true
    rabbitmq_host: 192.168.1.202
    redis_host: 192.168.1.202
    sensu_api_host: 192.168.1.202
  roles:
    - sensu-ansible


