---

- hosts: plex
  remote_user: root
  vars:
  tasks:

  - name: Shut down plexmediaserver
    systemd:
      name: plexmediaserver
      state: stopped

  - name: Delete cache data before backup
    file:
      path: "{{ plexDatabase }}/Cache"
      state: absent

  - name: Delete crash reports before backup
    file:
      path: "{{ plexDatabase }}/Crash Reports"
      state: absent

  - name: backup plex database
    archive:
      path: "{{ plexDatabase }}"
      dest: "{{ backupDirectory }}/plex-backup.{{ ansible_date_time.epoch }}.tgz"
      format: gz
#      exclude_path:
#        - "{{ plexDatabase }}Cache"

  - name: Start plexmediaserver
    systemd:
      name: plexmediaserver
      state: started
      enabled: yes


