---

- name: Add the ombi key
  apt_key:
    url: "https://repo.ombi.turd.me/pubkey.txt"
    state: present

- name: Ensure the Ombi APT repo is present
  apt_repository:
    repo: "deb http://repo.ombi.turd.me/stable/ jessie main"
    state: present
    update_cache: true

- name: Ensure Ombi is installed
  apt:
    name: "ombi"
    state: "latest"

